"""add holidays table with date range and recurring

Revision ID: 018_holidays
Revises: 017_schedule_overrides
Create Date: 2026-03-10 20:59:14.297557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '018_holidays'
down_revision = '017_schedule_overrides'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('holiday_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_day_of_week', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date', 'name', 'tenant_id', name='uq_holidays_start_date_name_tenant')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_student_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attendance_marked_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attendance_class_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['marked_by'], ['id'])
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('class_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('class_teachers_class_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('class_teachers_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('classes_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('fee_structure_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structure_classes_academic_year_id'), ['academic_year_id'], unique=False)

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_notification_templates_global'), postgresql_where='(tenant_id IS NULL)')
        batch_op.drop_index(batch_op.f('uq_notification_templates_tenant'), postgresql_where='(tenant_id IS NOT NULL)')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('features_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_roles_name_tenant'))
        batch_op.create_unique_constraint('uq_roles_name_tenant', ['name', 'tenant_id'])
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=False)
        batch_op.drop_constraint(batch_op.f('students_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('students_class_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)

    with op.batch_alter_table('teacher_workload_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_workload_teacher_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_teacher_workload_rules_teacher_id'))
        batch_op.create_index(batch_op.f('ix_teacher_workload_rules_teacher_id'), ['teacher_id'], unique=True)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_employee_id'), ['employee_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('teachers_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_plan_id'), ['plan_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_users_email_tenant'))
        batch_op.create_unique_constraint('uq_users_email_tenant', ['email', 'tenant_id'])
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_constraint('uq_users_email_tenant', type_='unique')
        batch_op.create_index(batch_op.f('uq_users_email_tenant'), ['email', 'tenant_id'], unique=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_plan_id'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teachers_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_teachers_employee_id'))

    with op.batch_alter_table('teacher_workload_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_workload_rules_teacher_id'))
        batch_op.create_index(batch_op.f('ix_teacher_workload_rules_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_workload_teacher_id'), ['teacher_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('students_class_id_fkey'), 'classes', ['class_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('students_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_constraint('uq_roles_name_tenant', type_='unique')
        batch_op.create_index(batch_op.f('uq_roles_name_tenant'), ['name', 'tenant_id'], unique=True)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('features_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_created_by'))

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_notification_templates_tenant'), ['tenant_id', 'type', 'channel'], unique=True, postgresql_where='(tenant_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_notification_templates_global'), ['type', 'channel'], unique=True, postgresql_where='(tenant_id IS NULL)')

    with op.batch_alter_table('fee_structure_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structure_classes_academic_year_id'))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('classes_teacher_id_fkey'), 'users', ['teacher_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('class_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_teachers_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('class_teachers_class_id_fkey'), 'classes', ['class_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_class_id_fkey'), 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('attendance_marked_by_fkey'), 'users', ['marked_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('attendance_student_id_fkey'), 'students', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_holidays_start_date'))
        batch_op.drop_index(batch_op.f('ix_holidays_end_date'))
        batch_op.drop_index(batch_op.f('ix_holidays_academic_year_id'))

    op.drop_table('holidays')
    # ### end Alembic commands ###
